### ISSUE TITLE
Why QT6

### ISSUE THREAD

**Issue by sergeevabc** [Coolcord/Hexagon#1]
Dear @Coolcord, why exactly did you move to QT6? Thus, you have effectively cut off Windows 7 users. And what for, new shiny buttons? You app is a simple tool to create and apply patches, there is no rocket science under the hood, almost zero surface for security issues. Look around: [CrowTranslate](https://crow-translate.github.io/), [DB Browser for SQLite](https://sqlitebrowser.org/), [GMIC](https://gmic.eu/), [Icecream Ebook Reader](https://icecreamapps.com/Ebook-Reader/), [Nauz File Detector](https://github.com/horsicq/Nauz-File-Detector) and [OceanAudio](https://www.ocenaudio.com/), to name a few apps, get by with QT5 just fine.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Coolcord** [comment]
Apologies for the delay responding. I've been pretty busy lately, so I haven't had much time to keep up with my projects. I do appreciate your feedback!

Long story short, I don't have any plans to support Qt5 (and as a result, Windows 7) anymore. I moved on to Qt6 for multiple reasons, mostly for the new developer libraries that come along with it. This move was also done to keep all of my current Qt projects unified and consistent for the new build process. But you are right from a user perspective: all that changes is 64-bit builds and the buttons look newer.

It's worth noting that there have been no major changes to Hexagon since the last update, so I'd just recommend running v1.1.1-1 for now. However, if you want to compile this project yourself using Qt5, you can do so in a similar fashion to how I've described here: https://github.com/Coolcord/Level-Headed/issues/35#issuecomment-1689284991

If there's a large demand for Windows 7 support in the future, I may consider providing Qt5 builds along with new releases, but I can't make any promises on this, as I maintain this on my free time. If someone else wants to do the legwork in supporting Windows 7, I'd gladly welcome it!
